### PR TITLE
Simplify the way the maintenance window is specified

### PR DESCRIPTION
**Pull request by majst01**
We actually have a broken way to configure the maintenance window. With this Breaking Change we hopefully make the backend implementation more robust.

BREAKING

### CODE REVIEW

**Comment by simcod** [comment]
@majst01 Due to compatibility issues with different module declarations in the generated files from the api and the console, we updated the `tsconfig.json` file to align the javascript module export declarations.

**Comment by majst01** [comment]
> @majst01 Due to compatibility issues with different module declarations in the generated files from the api and the console, we updated the `tsconfig.json` file to align the javascript module export declarations.

Cannot qualify this change, but trust you. Other than that looks good.

**Comment by majst01** [comment]
Approval must be done by @Pilzington or @iljarotar because i was the initial creator of this PR and cannot approve myself

**Comment by Pilzington** [comment]
> > @majst01 Due to compatibility issues with different module declarations in the generated files from the api and the console, we updated the `tsconfig.json` file to align the javascript module export declarations.
> 
> Cannot qualify this change, but trus

**Review by Pilzington — APPROVED** [review]
We did the module change with @iljarotar together.

**Pull request merged**
