### PR TITLE
RFC: ProjectRevision

### PR DESCRIPTION
**Pull request by majst01**
The ProjectRevision WatchRevision Stream should simplify and speed up the update of views in the console.

The Idea is that the api-server will increment the revision (maybe with the projectinterceptor) and in the console a stream to the projectrevision is open, and on a change of that the view can update the content.

@iljarotar @vknabel @Pilzington @Gerrit91 Would love your comments.

### CODE REVIEW

**Comment by majst01** [comment]
> From the front end point of view the question is, which resources we want to keep in sync across multiple tabs. For example, if I have the billing address view open in two different tabs and I change the address in one of them, should the other tab be notified about this?
> 
> So the question is, does every resource, that can be fetched, need to be synchronized across tabs, or is this only important for clusters, volumes and ips?

Thats why i introduced ResourceRevisions also, if the billing address changes, and we increment the revision their as well, you can update this view if you want.

But you are right, we should probably define which resources are relevant.

**Comment by iljarotar** [comment]
I see, that makes sense. So if we only need to update the cluster, volume or ip lists, we can ask for their revisions specifically, and if we need to synchronize any of the other resources, we can simply ask for the revision field of ProjectServiceWatchRevisionResponse?

**Comment by majst01** [comment]
> I see, that makes sense. So if we only need to update the cluster, volume or ip lists, we can ask for their revisions specifically, and if we need to synchronize any of the other resources, we can simply ask for the revision field of ProjectServiceWatchRevisionResponse?

This was my intention

**Comment by majst01** [comment]
Closing because old and wont fix the problem

**Pull request closed without merging**
