### PR TITLE
add azure provider

### PR DESCRIPTION
**Pull request by vknabel**
Implements a part of metal-stack-cloud/api-server#111. Is part of a group of PRs which need to be tested together:
- https://github.com/metal-stack-cloud/api/pull/10
- https://github.com/metal-stack-cloud/deployment/pull/21
- https://github.com/metal-stack-cloud/api-server/pull/125

Most of the diffs were required to fix an error (https://github.com/bufbuild/buf/issues/1380) by `buf mod update`.

Adds `O_AUTH_PROVIDER_AZURE`.

### CODE REVIEW

**Comment by vknabel** [comment]
Though I am not sure why the js files got removed. Aren't they used anymore? Do I need to run an additional command?

**Comment by majst01** [comment]
> Though I am not sure why the js files got removed. Aren't they used anymore? Do I need to run an additional command?

Did you simply run `make` ?

**Comment by vknabel** [comment]
Thanks! I did only run a different make command (can't remember which one).

**Comment by majst01** [comment]
looks better now

**Review by majst01 — APPROVED** [review]

**Comment by majst01** [comment]
Is this ready to merge ?

**Comment by vknabel** [comment]
Yes, this is now ready to merge. I guess this won't change anytime soon. :+1:

**Pull request merged**
